'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class LandingPage
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''HyperLink1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink1 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''CurrentUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CurrentUser As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Logout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Logout As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''Saws_AllBladesDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Saws_AllBladesDataSource As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''Saws_AllStatusesDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Saws_AllStatusesDataSource As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''Saws_AllDefectReasonsDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Saws_AllDefectReasonsDataSource As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''Saws_AllManufacturersDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Saws_AllManufacturersDataSource As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''Saws_AllLocationsDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Saws_AllLocationsDataSource As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''Saws_AllReworkNullDateIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Saws_AllReworkNullDateIn As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''GetReportsNames control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GetReportsNames As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''BladesDataGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BladesDataGrid As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''Tabcontainer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tabcontainer1 As Global.AjaxControlToolkit.TabContainer
    
    '''<summary>
    '''Reports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Reports As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''ReportSelector1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReportSelector1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''RR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RR As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ReportViewer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReportViewer As Global.Microsoft.Reporting.WebForms.ReportViewer
    
    '''<summary>
    '''ObjectDataSource1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ObjectDataSource1 As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''B_M control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents B_M As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''TabContainer2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabContainer2 As Global.AjaxControlToolkit.TabContainer
    
    '''<summary>
    '''Blades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Blades As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''BladesSerialText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BladesSerialText As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BladesSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BladesSearch As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BladeSearchMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BladeSearchMsg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BladeSearchYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BladeSearchYes As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BladeSearchNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BladeSearchNo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hardRule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hardRule As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''BladeContentDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BladeContentDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''BladeResultSerial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BladeResultSerial As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ManufacturersList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ManufacturersList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''SubmitNewMan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitNewMan As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''StatusList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''SubmitNewStat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitNewStat As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''LocationList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LocationList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DefLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DefLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DefectList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DefectList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''SubmitNewDefect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitNewDefect As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BladeDiameter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BladeDiameter As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BladeGrit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BladeGrit As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BladeThickness control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BladeThickness As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BladeResultInsert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BladeResultInsert As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BladeResultDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BladeResultDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ScrappedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScrappedBy As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BladeScrappedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BladeScrappedBy As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DateScrapped control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DateScrapped As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BladeScrapDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BladeScrapDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BladesEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BladesEdit As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BladesOutForRework control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BladesOutForRework As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BladesScrapped control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BladesScrapped As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BladesSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BladesSubmit As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BladesOFRSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BladesOFRSubmit As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BladesCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BladesCancel As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''NewBladeContentDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewBladeContentDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''BladesSerialNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BladesSerialNumber As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ManufacturersList2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ManufacturersList2 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''SubmitNewMan2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitNewMan2 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''StatusList2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusList2 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''LocationList2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LocationList2 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''BladeDiameter2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BladeDiameter2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BladeGrit2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BladeGrit2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BladeThickness2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BladeThickness2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BladesSubmit2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BladesSubmit2 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BladesCancel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BladesCancel2 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''RD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RD As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''ReworkBladeSerial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReworkBladeSerial As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DisplayReworkBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DisplayReworkBtn As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ReworkBladeDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReworkBladeDetails As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ReworkDateOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReworkDateOut As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ReworkReasonOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReworkReasonOut As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ReworkDateIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReworkDateIn As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ReworkCalendar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReworkCalendar As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''ReworkStatusList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReworkStatusList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ReworkThickness control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReworkThickness As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ReworkRunOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReworkRunOut As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ReworkSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReworkSubmit As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ReworkCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReworkCancel As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ReworkScrapBut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReworkScrapBut As Global.System.Web.UI.WebControls.Button
End Class
